package io.github.flyingpig525.base.block.subaction

import io.github.flyingpig525.base.block.subaction.SubAction

enum class IfPlayerSubAction(override val codeblock: String) : SubAction {
	IsLookingAt("IsLookingAt"),
	InWorldBorder("InWorldBorder"),
	IsInGameMode("IsInGameMode"),
	HasRoomForItem("PHasRoomForItem"),
	IsHoldingOff("IsHoldingOff"),
	UsingPack("UsingPack"),
	NoItemCooldown("NoItemCooldown"),
	IsUsingItem("IsUsingItem"),
	HasAllItems("HasAllItems"),
	IsSwimming("IsSwimming"),
	HasItem("HasItem"),
	BlockEquals("BlockEquals"),
	IsWearing("PIsWearing"),
	IsNear("PIsNear"),
	IsRiding("IsRiding"),
	StandingOn("PStandingOn"),
	CmdEquals("CmdEquals"),
	IsGrounded("IsGrounded"),
	CursorItem("CursorItem"),
	SlotEquals("SlotEquals"),
	ItemEquals("ItemEquals"),
	IsHoldingMain("IsHoldingMain"),
	IsHolding("IsHolding"),
	MenuSlotEquals("MenuSlotEquals"),
	IsBlocking("IsBlocking"),
	HasPermission("HasPermission"),
	MainHandEquals("MainHandEquals"),
	IsSneaking("IsSneaking"),
	IsFlying("IsFlying"),
	HasPotion("HasEffect"),
	NameEquals("PNameEquals"),
	InvOpen("InvOpen"),
	HasSlotItem("HasSlotItem"),
	IsSprinting("IsSprinting"),
	IsGliding("IsGliding"),
	CmdArgEquals("CmdArgEquals"),
}