package io.flyingpig525.base.block.subaction

enum class IfVarSubAction(codeblock: String) : SubAction(codeblock) {
	LessThanOrEqual("<="),
	ItemHasEnchant("ItemHasEnchant"),
	ItemIsBlock("ItemIsBlock"),
	DictValueEquals("DictValueEquals"),
	ItemHasTag("ItemHasTag"),
	StringMatches("StringMatches"),
	ListIsEmpty("ListIsEmpty"),
	StartsWith("StartsWith"),
	ListValueEq("ListValueEq"),
	VarIsType("VarIsType"),
	TextMatches("TextMatches"),
	IsNear("IsNear"),
	InRange("InRange"),
	VarExists("VarExists"),
	LegacyNotEqual("Legacy !="),
	BlockIsSolid("BlockIsSolid"),
	ItemEquals("ItemEquals"),
	ListContains("ListContains"),
	LegacyEquals("Legacy ="),
	InRange("InRange"),
	LocIsNear("LocIsNear"),
	Contains("Contains"),
	NotEqual("!="),
	LessThan("<"),
	EqualTo("="),
	GreaterThan(">"),
	EndsWith("EndsWith"),
	GreaterThanOrEqual(">="),
	DictHasKey("DictHasKey"),
}