/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.github.flyingpig525.base.Template
import io.github.flyingpig525.base.item.type.NumItem
import io.github.flyingpig525.base.item.type.NumItem.Companion.toNumItem
import io.github.flyingpig525.base.item.type.StringItem.Companion.toStringItem
import io.github.flyingpig525.base.item.type.VarItem
import io.github.flyingpig525.base.item.type.VarItem.Companion.toVarItem
import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val temp = Template(Template.Type.PROCESS) {
            val list = "list".toVarItem(VarItem.Scope.LOCAL)
            SetVariable.chain {
                increment {
                    +"hello".toVarItem()
                    +(12.toNumItem())
                }
                root {
                    +"root".toVarItem(VarItem.Scope.LOCAL)
                    +(36.toNumItem())
                }
                createList {
                    +list
                    +"Hello KotlinFire world!".toStringItem()
                    +"Welcome to KotlinFire".toStringItem()
                }
            }
            PlayerAction.sendMessage {
                +list
            }

        }
        println(temp.getTemplateString())
        println(temp.getJsonData())
        Template.codeClientPlaceTemplate(temp)
    }
}
