/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.github.flyingpig525.base.item.VarItem
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val varItem = VarItem("%default", VarItem.Scope.LOCAL)
        val string = Json.encodeToString(varItem)
        println(string)
    }
}
