/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.github.flyingpig525.base.Template
import io.github.flyingpig525.base.item.type.NumItem
import io.github.flyingpig525.base.item.type.VarItem
import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val temp = Template {
            setVar {
                +VarItem("%default", VarItem.Scope.LOCAL)
                +NumItem(12)
            }
        }
        println(temp.getTemplateString())
        println(temp.getJsonData())
        Template.codeClientPlaceTemplate(temp)
    }
}
